### ISSUE TITLE
Contributions of Year 2016

### ISSUE THREAD

**Issue by nomadicmehul** [mozguj/Events#1]
Hey Awesome people, 

Hope you all are doing good. 

Please add your blog post of open source events where you have participated / gave talks / organized in Year 2016.

Contributions done by group, individual also as a single blog post.

P.S. You can use below format : 
**Example :** 

1. Event Name : 
2. Event Link (Reps/Facebook Event/Any link) : 
3. Blog post : 
4. Photo Album link (Flicker/Drive/Drop Box/Any) : 
5. Date/Month :
 

**Last date to submit : March 31st 2017.** 

Cheers! 
Mehul Patel.
**On Behalf of [Mozilla Gujarat](http://blog.mozillagujarat.org/).**

**Comment by rnikhil33** [comment]
Hi Everyone,

Below is the details of Maker Party Gujarat 2016.

1. Event Name: Maker Party 2k16
2. Event Link: https://reps.mozilla.org/e/maker-party-gujarat/
3. Blog post: https://moznik.wordpress.com/2016/11/11/maker-party-gujarat/
4. Photo Album link: https://www.flickr.com/photos/145251384@N03/albums/72157674389111250
5. Date: 18th and 19th October 2016.

Thank you.

Regards,
Nikhil Patel

**Comment by vyaspranjal33** [comment]
Event Name: Maker Party 2016
Event Link: https://reps.mozilla.org/e/maker-party-gujarat/
Blog post: [https://pranjalvyas.wordpress.com/2016/10/20/mozilla-maker-party-2016/]
Photo Album link: [https://www.flickr.com/photos/145251384@N03/albums/72157674389111250]
Date: 18th and 19th October 2016.

**Comment by ghost** [comment]
1) Event name :- MOZCONNECT AT GTU (GUJARAT TECHNICAL UNIVERSITY)
2) blog post :- https://haardpatelblog.wordpress.com/2016/06/21/mozconnect-at-gtu-gujarat-technical-university/
3) event link :-  https://reps.mozilla.org/e/mozilla-connect-gtu/

1) Event name :- MOZCONNECT AT IET AHMEDABAD
2) Event blog :- https://haardpatelblog.wordpress.com/2016/06/21/mozconnect-at-iet-ahmedabad/
3) Event link :-  https://reps.mozilla.org/e/mozconnect-ahmedabad-university/

1) Event name :- George Roter visit to ahmedabad
2) Event blog :- https://haardpatelblog.wordpress.com/2016/06/03/george-visit-to-ahmedabad/
3) Event date :- 31/4/2016

Thank you

Regards 
Haard patel
