### ISSUE TITLE
Contributions of Month January 2017

### ISSUE THREAD

**Issue by nomadicmehul** [mozguj/Events#2]
Hey Awesome people, 

Hope you all are doing good. 

Please add your blog post of open source events where you have participated / gave talks / organized in January 2017..

Contributions done by group, individual also as a single blog post.

P.S. You can use below format : 
**Example :** 

1. Event Name : 
2. Event Link (Reps/Facebook Event/Any link) : 
3. Blog post : 
4. Photo Album link (Flicker/Drive/Drop Box/Any) : 
5. Date :

Cheers! 
Mehul Patel.
**On Behalf of [Mozilla Gujarat](http://blog.mozillagujarat.org/).**

**Comment by vyaspranjal33** [comment]
Event Name : A day of Virtual Reality
Event Link : [https://reps.mozilla.org/e/a-day-of-virtual-reality-1/]
Blog post : [https://pranjalvyas.wordpress.com/2017/01/21/a-day-of-virtual-reality/]
Photo Album link (Flicker/Drive/Drop Box/Any) : N/A
Date : 19th january 2017

**Comment by vyaspranjal33** [comment]
Event Name : Privacy brigade
Event Link : [https://reps.mozilla.org/e/privacy-brigade/]
Blog post : [https://pranjalvyas.wordpress.com/2017/01/21/privacy-brigade/]
Photo Album link (Flicker/Drive/Drop Box/Any) : N/A
Date : 20th january 2017
