### ISSUE TITLE
Contributions of Month Feb 2017

### ISSUE THREAD

**Issue by nomadicmehul** [mozguj/Events#3]
Hey Awesome people, 

Hope you all are doing good. 

Please add your blog post of open source events where you have participated / gave talks / organized in Feb 2017.

Contributions done by group, individual also as a single blog post.

P.S. You can use below format : 
**Example :** 

1. Event Name : 
2. Event Link (Reps/Facebook Event/Any link) : 
3. Blog post : 
4. Photo Album link (Flicker/Drive/Drop Box/Any) : 
5. Date :

Cheers! 
Mehul Patel.
**On Behalf of [Mozilla Gujarat](http://blog.mozillagujarat.org/).**

**Comment by vyaspranjal33** [comment]
Event Name : Basics Of wordpress
Event Link  : N/A
Blog post : [https://pranjalvyas.wordpress.com/2017/02/22/basics-of-wordpress/]
Photo Album link (Flicker/Drive/Drop Box/Any) : N/A
Date : 22nd February 2017

**Comment by vyaspranjal33** [comment]
Event Name : Privacy Brigade
Event Link : N/A
Blog post : [https://pranjalvyas.wordpress.com/2017/03/15/privacy-brigade-gp-ahmedabad/]
Photo Album link (Flicker/Drive/Drop Box/Any) : N/A
Date : 28th February 2017

**Comment by rnikhil33** [comment]
Event Name : Inauguration of Mozilla Nirma Chapter 
Event Link : https://reps.mozilla.org/e/mozilla-nirama-campus-club-inagaration/
Blog post : https://moznik.wordpress.com/2017/04/01/inauguration-of-mozilla-nirma-chapter/
Photo Album link (Flicker/Drive/Drop Box/Any) : N/A
Date : 13th February 2017
