### ISSUE TITLE
Contributions of Month March 2017

### ISSUE THREAD

**Issue by nomadicmehul** [mozguj/Events#4]
Hey Awesome people, 

Hope you all are doing good. 

Please add your blog post of open source events where you have participated / gave talks / organized in March 2017.

Contributions done by group, individual also as a single blog post.

P.S. You can use below format : 
**Example :** 

1. Event Name : 
2. Event Link (Reps/Facebook Event/Any link) : 
3. Blog post : 
4. Photo Album link (Flicker/Drive/Drop Box/Any) : 
5. Date :

**Last date to submit : March 31st 2017.** 

Cheers! 
Mehul Patel.
**On Behalf of [Mozilla Gujarat](http://blog.mozillagujarat.org/).**

**Comment by vyaspranjal33** [comment]
Event Name : Privacy Brigade
Event Link : https://reps.mozilla.org/e/privacy-brigade-1/
Blog post : [https://pranjalvyas.wordpress.com/2017/04/17/privacy-brigade-gp-gandhinagar/]
Photo Album link (Flicker/Drive/Drop Box/Any) : N/A
Date : 30th March 2017
